sudo: false

language: python

python:
  - "3.7"

jdk:
  - openjdk17
  
services:
  - xvfb

before_install:
  - sudo apt-get install graphviz

install:
  - pip3 install bikeshed && bikeshed update

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    
script:
  - ./gradlew build generateDocs --refresh-dependencies

env:
  global:
  - ENCRYPTION_LABEL: "26c87bd483ba"
  - COMMIT_AUTHOR_EMAIL: "melaasar@gmail.com"

deploy:
  - provider: script
    script: .deploy/deploy.sh
    skip_cleanup: true
    on:
      tags: false
      branch: master
  - provider: script
    script: ./gradlew publish
    skip_cleanup: true
    on:
      tags: true
      branch: master
